services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.2-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USER}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_PASSWORD=${DB_PASSWORD}

  laravel:
    tty: true
    image: docker.io/bitnami/laravel:${LARAVEL_VERSION}-debian-10
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - privileged=${LARAVEL_PRIVILEGED}
    depends_on:
      - mariadb
    ports:
      - '${LARAVEL_HTTP_PORT}:3000'
    volumes:
      - '${APP_CODE_PATH_HOST}:/app'
