#User defined
user:
  backend_ws:
    label:
      Laravel Version
    hint:
      Select a laravel version
    type:
      select
    values:
      - 6
      - 7
      - 8
    target:
      LARAVEL_VERSION

    enable_privileged:
    label:
      Enable privileged?
    type:
      checkbox
    hint:
      Privileged mode could be required to run this container under Windows
    target:
      LARAVEL_PRIVILEGED

  # run_cron:
  #   label:
  #     Run cron jobs?
  #   type:
  #     checkbox
  #   hint:
  #     Check to enable cron jobs
  #   target:
  #     MAUTIC_RUN_CRON
  # mysql_version:
  #   label:
  #     MySQL version
  #   hint:
  #     Select MySQL version
  #   type:
  #     select
  #   values:
  #     - "5.0"
  #     - "7.0"
  #   target:
  #     MYSQL_VERSION

#System defaults
system:
  show_localpath_selector:
    true
  #For collecting and storing DB in .env
  #db/user/password
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http: LARAVEL_HTTP_PORT
    others: