FROM ghcr.io/deck-app/apache:v7.4
LABEL maintainer Naba Das <hello@get-deck.com>

# Persistent runtime dependencies
# Example RUN apk add --no-cache php7-openssl php7-sysvmsg php7-curl

RUN mkdir -p /app
RUN mkdir -p /var/preview
COPY httpd.conf /etc/apache2/httpd.conf
COPY httpd.conf /app/httpd.conf
RUN wget -O /var/preview/index.html https://raw.githubusercontent.com/deck-app/stack-preview-screen/main/install/index.html
RUN sed -i "s#{SERVER_ROOT}#/var/preview#g" /etc/apache2/httpd.conf
RUN sed -i "s#{SERVER_ROOT}#/var/www/public#g" /app/httpd.conf

WORKDIR /var/www

COPY php_ini/php.ini /etc/php7/php.ini
ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php7/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php7/php.ini \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
apk add php7-pecl-xdebug \
&& echo "zend_extension=xdebug" >> /etc/php7/php.ini \
;fi

ARG INSTALL_ADDITIONAL_EXTENSIONS
RUN if [ -z "$INSTALL_ADDITIONAL_EXTENSIONS" ] ; then \
echo "No additional PHP extensions added" \
;else \
apk add --no-cache ${INSTALL_ADDITIONAL_EXTENSIONS} \
;fi

RUN apk add php7-zip openssh mercurial tzdata openntpd
RUN apk add zip apache2 apache2-utils
ARG LARAVEL_VERSION
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN sed -i "s#{LARAVEL_VERSION}#${LARAVEL_VERSION}#g" /docker-entrypoint.sh
RUN rm -f /var/run/apache2/httpd.pid
RUN chmod +x /docker-entrypoint.sh

# User ID defined
ARG USER_ID
RUN if [ ${USER_ID} -gt 0 ]; then \
	apk --no-cache add shadow && \
    	usermod -u ${USER_ID} nobody && \
    	groupmod -g ${USER_ID} nobody \
;fi
RUN sed -i "s#{USER_ID}#${USER_ID}#g" /docker-entrypoint.sh

CMD /docker-entrypoint.sh & /sbin/runit-wrapper