FROM ghcr.io/deck-app/apache:v8.0
LABEL maintainer Naba Das <hello@get-deck.com>

# Persistent runtime dependencies
# Example RUN apk add --no-cache php8-openssl php8-sysvmsg php8-curl


COPY httpd.conf /etc/apache2/httpd.conf
RUN ln -s /usr/bin/php /usr/bin/php8


WORKDIR /var/www
COPY php_ini/php8.0.ini /etc/php8/php.ini

ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php8/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php8/php.ini \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
apk add php8-pecl-xdebug \
&& echo "zend_extension=xdebug" >> /etc/php8/php.ini \
;fi

RUN apk add php8-zip
RUN apk add zip
ARG LARAVEL_VERSION
COPY docker-entrypoint${LARAVEL_VERSION}.sh /docker-entrypoint.sh
#LARAVEL_INSTALL enable or disable
ARG LARAVEL_INSTALL
RUN if [ ${LARAVEL_INSTALL} = true ]; then \
sed -i "s#{LARAVEL_INSTALL}#true#g" /docker-entrypoint.sh \
;else \
sed -i "s#{LARAVEL_INSTALL}#false#g" /docker-entrypoint.sh \
;fi
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/sbin/runit-wrapper"]