name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - name: nginx php8 laravel8 Docker image
      run: docker-compose build
        image: 'nginx/Dockerfile-8.0'
        args:
          - ${{LARAVEL_VERSION}}
