name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Laravel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the image
        run: docker-compose build --build-arg LARAVEL_VERSION="7" --build-arg BACK_END="nginx" --build-arg PHP_VERSION="7.4" --tag apache:v7.4 .