name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
        BACK_END: nginx apache
        PHP_VERSION: 7.4 8.0
        LARAVEL_VERSION: 7 8
        using: '${{BACK_END}}/docker-${{PHP_VERSION}}'
