name: LARAVEL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Laravel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the image with php 8.2 Laravel 10 and nginx
        run: docker-compose -f "docker-compose.yml" up -d --build
        env:
          PHP_VERSION: "8.2"
          LARAVEL_VERSION: 10
          BACK_END: nginx
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.1 Laravel 10 and nginx
        run: docker-compose -f "docker-compose.yml" up -d --build
        env:
          PHP_VERSION: "8.1"
          LARAVEL_VERSION: 10
          BACK_END: nginx
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.1 Laravel 9 and nginx
        run: docker-compose -f "docker-compose.yml" up -d --build
        env:
          PHP_VERSION: "8.1"
          LARAVEL_VERSION: 9
          BACK_END: nginx
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.1 Laravel 8 and nginx
        run: docker-compose -f "docker-compose.yml" up -d --build
        env:
          PHP_VERSION: "8.1"
          LARAVEL_VERSION: 8
          BACK_END: nginx
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.0 Laravel 9 and nginx
        run: docker-compose -f "docker-compose.yml" up -d --build
        env:
          PHP_VERSION: "8.0"
          LARAVEL_VERSION: 9
          BACK_END: nginx
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.0 Laravel 8 and nginx
        run: docker-compose -f "docker-compose.yml" up -d --build
        env:
          PHP_VERSION: "8.0"
          LARAVEL_VERSION: 8
          BACK_END: nginx
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.0 Laravel 7 and nginx
        run: docker-compose build
        env:
          PHP_VERSION: "8.0"
          LARAVEL_VERSION: 7
          BACK_END: nginx
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 7.4 Laravel 8 and nginx
        run: docker-compose build
        env:
          PHP_VERSION: "7.4"
          LARAVEL_VERSION: 8
          BACK_END: nginx
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 7.4 Laravel 7 and nginx
        run: docker-compose build
        env:
          PHP_VERSION: "7.4"
          LARAVEL_VERSION: 7
          BACK_END: nginx
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.2 Laravel 10 and apache
        run: docker-compose build
        env:
          PHP_VERSION: "8.2"
          LARAVEL_VERSION: 10
          BACK_END: apache
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.1 Laravel 10 and apache
        run: docker-compose build
        env:
          PHP_VERSION: "8.1"
          LARAVEL_VERSION: 10
          BACK_END: apache
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.1 Laravel 9 and apache
        run: docker-compose build
        env:
          PHP_VERSION: "8.1"
          LARAVEL_VERSION: 9
          BACK_END: apache
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.1 Laravel 8 and apache
        run: docker-compose build
        env:
          PHP_VERSION: "8.1"
          LARAVEL_VERSION: 8
          BACK_END: apache
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.0 Laravel 9 and apache
        run: docker-compose build
        env:
          PHP_VERSION: "8.0"
          LARAVEL_VERSION: 9
          BACK_END: apache
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.0 Laravel 8 and apache
        run: docker-compose build
        env:
          PHP_VERSION: "8.0"
          LARAVEL_VERSION: 8
          BACK_END: apache
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.0 Laravel 7 and apache
        run: docker-compose build
        env:
          PHP_VERSION: "8.0"
          LARAVEL_VERSION: 7
          BACK_END: apache
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 7.4 Laravel 8 and apache
        run: docker-compose build
        env:
          PHP_VERSION: "7.4"
          LARAVEL_VERSION: 8
          BACK_END: apache
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 7.4 Laravel 7 and apache
        run: docker-compose build
        env:
          PHP_VERSION: "7.4"
          LARAVEL_VERSION: 7
          BACK_END: apache
          LARAVEL_INSTALL: true
          XDEBUG: true
          DISPLAY_PHPERROR: true